services:
  snake-game:
    container_name: snake-game
    image: ghcr.io/hackysphere/snake-game:latest
    ports:
      - 8012:8012
    environment:
      APP_URL: "http://YOUR.DOMAIN:8012"
      USING_TRUSTED_PROXY: false
      NODE_LOG_LEVEL: "info"
